name: typst

on:
  workflow_run:
    workflows: ["verify"]
    types:
      - completed

jobs:
  typst:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Install dependencies
      run: pip3 install -U online-judge-verify-helper
    - name: Generate stats
      run: oj-verify stats -j 4 > stats.json
    - name: Install Typst
      run: |
        curl -Lo typst.tar.gz https://github.com/typst/typst/releases/download/v0.13.0/typst-x86_64-unknown-linux-musl.tar.xz
        tar xf typst.tar.gz
    - name: Compile notebook file
      run: |
        ./preprocess.py
        ./typst-x86_64-unknown-linux-musl/typst compile main.typ notebook.pdf
    - name: Delete old release
      continue-on-error: true
      run: |
        gh release delete master -y --cleanup-tag
    - name: Create release
      run: |
        gh release create master notebook.pdf
